# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${set_runs_dir:${paths.log_dir}/${task_name}/runs}/${process_dir_name:${hydra.job.override_dirname}}
sweep:
  dir: ${set_runs_dir:${paths.log_dir}/${task_name}/multiruns}
  subdir: ${process_dir_name:${hydra.job.override_dirname}}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log
